name: files-update
on:
  push:
    tags:
      - 'test-*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Download AWS JSON
        run: |
          wget 'https://ip-ranges.amazonaws.com/ip-ranges.json' -N -O files/aws.json
      - name: Download Azure JSON
        run: |
          wget "https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_$(date -v-monday +%Y%m%d).json" -N -O files/azure.json
      - name: Generate statik file
        run: |
          go get github.com/rakyll/statik
          statik -src=/files -dest=/pkg/ccidr -f
      - name: Commit new files
        uses: EndBug/add-and-commit@v4
        with:
          add: '.'
          author_name: Jean-Philippe Bond
          author_email: jeanp.bond.dev@gmail.com
          message: 'Update Public Cloud JSON files'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
